### PR TITLE
Added new notifications for memberships and releases

### PR DESCRIPTION
**Pull request by jvarness**
Full disclosure: I have not tested these webhooks out yet, but I followed the documentation from the README and have created two new notification events.

### CODE REVIEW

**Comment by jvarness** [comment]
I tested the releases notifications this morning. They seem to be working alright.

**Comment by michaeljacobdavis** [comment]
Awesome! Thanks for the contribution.

**Comment by michaeljacobdavis** [comment]
Published as `v2.0.0`

**Comment by jvarness** [comment]
@michaeljacobdavis thank you!

**Pull request merged**
